Move code of Help/Help.bash to global functions for future use

diff --git a/mitchellvanbijleveld b/mitchellvanbijleveld
--- a/mitchellvanbijleveld
+++ b/mitchellvanbijleveld
@@ -6,7 +6,7 @@
 ####################################################################################################
 # VAR_UTILITY="mitchell"
 # VAR_UTILITY_SCRIPT="vanbijleveld"
-VAR_UTILITY_SCRIPT_VERSION="2024.12.24-0134"
+VAR_UTILITY_SCRIPT_VERSION="2025.01.01-2321"
 VAR_UTILITY_SCRIPT_REQUIRED_COMMAND_LINE_TOOLS="awk basename bash date dirname echo eval exit find grep mktemp printf realpath sed shift tee tr type which"
 ####################################################################################################
 # BIN INFO - MITCHELL/VANBIJLEVELD
@@ -250,6 +250,40 @@ ForEachUtilityScript(){
     done
 }
 export -f ForEachUtilityScript
+#
+FindUtilitySubFolderPath(){
+    # $1 = SUB FOLDER NAME
+    PrintMessage "DEBUG" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "Checking variable HELP_VAR_UTILITY with value '$HELP_VAR_UTILITY'..."
+    if [[ $HELP_VAR_UTILITY == "" ]]; then
+        PrintMessage "FATAL" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "No $1 Utility was provided. Exiting..."
+        exit 1
+    fi
+    #
+    if FindUtilityFolderPath "$GLOBAL_VAR_DIR_INSTALLATION/$1" "$HELP_VAR_UTILITY"; then
+        PrintMessage "DEBUG" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "$1 Utility Folder '$HELP_VAR_UTILITY' found!"
+    else
+        PrintMessage "FATAL" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "The $1 Utility Folder for '$HELP_VAR_UTILITY' was not found. Exiting..."
+        exit 1
+    fi
+}
+export -f FindUtilitySubFolderPath
+#
+FindUtilityScriptSubFilePath(){
+    # $1 = SUB FOLDER NAME
+    if FindUtilityScriptFilePath "$VAR_UTILITY_FOLDER_PATH" "$HELP_VAR_UTILITY_SCRIPT"; then
+        PrintMessage "DEBUG" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "$1 Utility Script File '$HELP_VAR_UTILITY_SCRIPT' found in Utility '$HELP_VAR_UTILITY'!"
+    elif FindUtilityScriptFilePath "$VAR_UTILITY_FOLDER_PATH" "$HELP_VAR_UTILITY"; then
+        PrintMessage "DEBUG" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "Utility Script '$HELP_VAR_UTILITY' found in Utility '$HELP_VAR_UTILITY'!"
+        PrintMessage "DEBUG" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "Changing variable 'HELP_VAR_UTILITY_SCRIPT' from '$HELP_VAR_UTILITY_SCRIPT' to '$HELP_VAR_UTILITY'..."
+    elif [[ $HELP_VAR_UTILITY_SCRIPT == "" ]]; then
+        PrintMessage "FATAL" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "No $1 Utility Script was provided. Exiting..."
+        exit 1
+    else
+        PrintMessage "FATAL" "$VAR_UTILITY" "$VAR_UTILITY_SCRIPT" "The $1 Utility Script File for '$HELP_VAR_UTILITY' '$HELP_VAR_UTILITY_SCRIPT' was not found. Exiting..."
+        exit 1
+    fi
+}
+export -f FindUtilityScriptSubFilePath
 ####################################################################################################
 # FUNCTIONS
 ####################################################################################################
