Add flag to skip the dependency check

diff --git a/mitchellvanbijleveld b/mitchellvanbijleveld
--- a/mitchellvanbijleveld
+++ b/mitchellvanbijleveld
@@ -49,6 +49,9 @@ for var_argument in "$@"; do
         "--DEBUG")
             VAR_ENABLE_DEBUG=1
         ;;
+        "--SKIP-DEPENDENCY-CHECK")
+            VAR_SKIP_DEPENDENCY_CHECK=1
+        ;;
         "--UPDATE-FIRST")
             VAR_UPDATE_FIRST=1
         ;;
@@ -423,14 +426,18 @@ PrintMessage "CONFIG" "mitchell" "vanbijleveld" "UTILITY_SCRIPT_VAR_DIR_TMP   = 
 ####################################################################################################
 # CHECK DEPENDENCIES
 ####################################################################################################
-PrintMessage "DEBUG" "mitchell" "vanbijleveld" "Fetching dependencies from utility script..."
-eval_FromFile "VAR_UTILITY_SCRIPT_REQUIRED_COMMAND_LINE_TOOLS" $VAR_UTILITY_SCRIPT_FILE_PATH
-PrintMessage "DEBUG" "mitchell" "vanbijleveld" "Starting script to check dependencies..."
-$(which bash) "$GLOBAL_VAR_DIR_INSTALLATION/bin/CheckDependencies.bash" $VAR_UTILITY_SCRIPT_REQUIRED_COMMAND_LINE_TOOLS "--run-in-background"
-#
-if [[ $? -eq 1 ]]; then
-    PrintMessage "FATAL" "mitchell" "vanbijleveld" "Could not start Utility '$VAR_UTILITY' Script '$VAR_UTILITY_SCRIPT' because dependencies are missing. Exiting..."
-    exit 1
+if [[ $VAR_SKIP_DEPENDENCY_CHECK -eq 1 ]]; then
+    PrintMessage "DEBUG" "mitchell" "vanbijleveld" "Skipping dependency check..."
+else
+    PrintMessage "DEBUG" "mitchell" "vanbijleveld" "Fetching dependencies from utility script..."
+    eval_FromFile "VAR_UTILITY_SCRIPT_REQUIRED_COMMAND_LINE_TOOLS" $VAR_UTILITY_SCRIPT_FILE_PATH
+    PrintMessage "DEBUG" "mitchell" "vanbijleveld" "Starting script to check dependencies..."
+    $(which bash) "$GLOBAL_VAR_DIR_INSTALLATION/bin/CheckDependencies.bash" $VAR_UTILITY_SCRIPT_REQUIRED_COMMAND_LINE_TOOLS "--run-in-background"
+    #
+    if [[ $? -eq 1 ]]; then
+        PrintMessage "FATAL" "mitchell" "vanbijleveld" "Could not start Utility '$VAR_UTILITY' Script '$VAR_UTILITY_SCRIPT' because dependencies are missing. Exiting..."
+        exit 1
+    fi
 fi
 ####################################################################################################
 # CHECK DEPENDENCIES
